### ISSUE TITLE
Add $id to the generated TypeScript source

### ISSUE THREAD

**Issue by tet-lenovo** [xddq/schema2typebox#32]
Library version: 1.6.2

JSON schema version: draft-04, draft-06, draft-07, 2019-09, 2020-12

I am willing to contribute to fix the issue 💚

## The current behavior
Currently, TypeBox source is generated that looks something like this:

```
const obj1 = Type.Object({
    prop1: Type.String(),
    prop2: Type.String()
});
```

## The expected behavior

I would like it to include a top-level $id for everything generated:

```
const obj1 = Type.Object({
    prop1: Type.String(),
    prop2: Type.String()
}, {
    $id: "Obj1Id"
});
```

So I can reference it like this:

```
const obj2 = Type.Object({
    obj1: Type.Ref(obj1),
    other: Type.String()
}, {
    $id: "Obj2Id"
});
```

## Why does it happen? What/How to fix the issue?

I did hack together a quick "post processing" type change in the schema2typebox() function that does what I want.  Not sure if this is the best way to do it or not but it at least demonstrates what I am asking for.

```
...
    const exportedName = createExportNameForSchema(dereferencedSchema);
    const exportedType = createExportedTypeForName(exportedName);
    const start = typeBoxType.slice(0, typeBoxType.lastIndexOf(");"));
    const end = typeBoxType.slice(typeBoxType.lastIndexOf(");"));
    typeBoxType = `${start}, { $id: "${exportedName}" }${end}`;
    return `${createImportStatements()}

${typeBoxType.includes("OneOf([") ? (0, exports.createOneOfTypeboxSupportCode)() : ""}
${exportedType}
export const ${exportedName} = ${typeBoxType}`;
```

**Comment by xddq** [comment]
Hey!

Seems to be fine. Probably name it something like `addJsonSchemaIdToTypeboxType` which takes the typeBoxType and returns the code.

If you want, you are welcome to create a PR for this!

**Comment by tet-lenovo** [comment]
I started using this approach to add $id and broke the "schema.org - dayOfWeek" test since I just blindly insert $id based on ");".  I think there are two options: 1) I can check the code for "$id" and not insert one, 2) I can change collect() so that it passes the exportedName down to all of the parsers and inserts $id appropriately.  With option 1, it can still fail if the string "$id" is in any of the JSON text plus it only would work because that test happens to already include $id in the JSON schema.  Option 2 is probably the better way but more invasive.  Looking for some direction on the preferred approach.

**Comment by xddq** [comment]
Oh.. I see. If I am seeing this correctky I guess it is actually best to add the id right after we dereference the source schema [here](https://github.com/xddq/schema2typebox/blob/main/src/schema-to-typebox.ts#L38) into the object and let collect() do its work!

Basically, if dereferencedschema.$id is undefined, you can add `exportedName` (or whatever you think is best) to the id field. Otherwise do nothing with it.

Can you check this and perhaps send a PR if it works out?

**Comment by xddq** [comment]
Alright, still thanks for the effort! Will have a look in the coming weeks.

**Comment by xddq** [comment]
done in https://github.com/xddq/schema2typebox/pull/33

If you have issues please create a new one
